<script setup lang="ts">
    const today = (new Date()).toUTCString()
</script>

<template>
    <h1 class="text-5xl">Projects</h1>
    <h2 class="font-light text-sm mb-4">Last Updated {{ today }}</h2>
    <p class="text-lg mb-4"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam hendrerit elit vitae ante vestibulum, ut condimentum ante varius. Proin sagittis lacus eu feugiat feugiat. Maecenas finibus sagittis gravida. Ut rhoncus posuere faucibus. Duis eget vehicula velit. Suspendisse potenti. Vivamus iaculis risus a massa fringilla feugiat. Quisque posuere diam at lacus euismod porttitor. Integer pulvinar malesuada commodo. </p>
    <p class="text-lg mb-4"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam hendrerit elit vitae ante vestibulum, ut condimentum ante varius. Proin sagittis lacus eu feugiat feugiat. Maecenas finibus sagittis gravida. Ut rhoncus posuere faucibus. Duis eget vehicula velit. Suspendisse potenti. Vivamus iaculis risus a massa fringilla feugiat. Quisque posuere diam at lacus euismod porttitor. Integer pulvinar malesuada commodo. </p>
    <p class="text-lg mb-4"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam hendrerit elit vitae ante vestibulum, ut condimentum ante varius. Proin sagittis lacus eu feugiat feugiat. Maecenas finibus sagittis gravida. Ut rhoncus posuere faucibus. Duis eget vehicula velit. Suspendisse potenti. Vivamus iaculis risus a massa fringilla feugiat. Quisque posuere diam at lacus euismod porttitor. Integer pulvinar malesuada commodo. </p>
    <p class="text-lg mb-4"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam hendrerit elit vitae ante vestibulum, ut condimentum ante varius. Proin sagittis lacus eu feugiat feugiat. Maecenas finibus sagittis gravida. Ut rhoncus posuere faucibus. Duis eget vehicula velit. Suspendisse potenti. Vivamus iaculis risus a massa fringilla feugiat. Quisque posuere diam at lacus euismod porttitor. Integer pulvinar malesuada commodo. </p>
    <p class="text-lg mb-4"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam hendrerit elit vitae ante vestibulum, ut condimentum ante varius. Proin sagittis lacus eu feugiat feugiat. Maecenas finibus sagittis gravida. Ut rhoncus posuere faucibus. Duis eget vehicula velit. Suspendisse potenti. Vivamus iaculis risus a massa fringilla feugiat. Quisque posuere diam at lacus euismod porttitor. Integer pulvinar malesuada commodo. </p>
    <p class="text-lg mb-8"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam hendrerit elit vitae ante vestibulum, ut condimentum ante varius. Proin sagittis lacus eu feugiat feugiat. Maecenas finibus sagittis gravida. Ut rhoncus posuere faucibus. Duis eget vehicula velit. Suspendisse potenti. Vivamus iaculis risus a massa fringilla feugiat. Quisque posuere diam at lacus euismod porttitor. Integer pulvinar malesuada commodo. </p>
</template>